fix(gatt-database): remove database from dbs list when destroyed
btd_gatt_database_new() adds btd_gatt_database to the dbs lookup queue,
but nothing removes it from there even when destroying.

Fix by removing databases from the lookup queue before destroy.

Fixes crash on adapter removal in some cases:

ERROR: AddressSanitizer: heap-use-after-free on address 0x7bd476be1308
READ of size 8 at 0x7bd476be1308 thread T0
    #0 0x00000064562a in match_db
    #1 0x000000865410 in queue_find
    #2 0x000000645671 in btd_gatt_database_get
0x7bd476be1308 is located 8 bytes inside of 128-byte region [0x7bd476be1300,0x7bd476be>
freed by thread T0 here:
    #0 0x7f1478cee4cf in free.part.0
    #1 0x000000621625 in gatt_database_free
    #2 0x000000645582 in btd_gatt_database_destroy

Changes:
  - Add debian/patches/fix-gatt-database-remove-database-from-dbs-list-when-destroyed.patch
  - Modify debian/patches/series
  - Modify debian/changelog

Upstream: https://github.com/bluez/bluez/commit/1ab128f6d749427a5508592b3b2b587b724efccf

Generated-By: glm-5.2
Co-Authored-By: deepin-ci-robot <packages@deepin.org>